import {
	__DEFAULT_FORM_HELPER_TEXT_ALIGN__,
	__DEFAULT_FORM_HELPER_TEXT_LINE_CLAMP__,
	__DEFAULT_FORM_HELPER_TEXT_LINE_HEIGHT__
} from './props';

export {
	__DEFAULT_FORM_HELPER_TEXT_ALIGN__,
	__DEFAULT_FORM_HELPER_TEXT_LINE_CLAMP__,
	__DEFAULT_FORM_HELPER_TEXT_LINE_HEIGHT__
};
