import {
	__DEFAULT_CONFIRM_MODAL_TRANSITION_INITIAL_SCALE__,
	__DEFAULT_CONFIRM_MODAL_TRANSITION_TRANSITION__,
	__DEFAULT_CONFIRM_MODAL_TRANSITION_VARIANT__
} from './props';

export {
	__DEFAULT_CONFIRM_MODAL_TRANSITION_INITIAL_SCALE__,
	__DEFAULT_CONFIRM_MODAL_TRANSITION_TRANSITION__,
	__DEFAULT_CONFIRM_MODAL_TRANSITION_VARIANT__
};
