import {
	__DEFAULT_FORM_DESCRIPTION_ALIGN__,
	__DEFAULT_FORM_DESCRIPTION_LINE_CLAMP__,
	__DEFAULT_FORM_DESCRIPTION_LINE_HEIGHT__
} from './props';

export {
	__DEFAULT_FORM_DESCRIPTION_ALIGN__,
	__DEFAULT_FORM_DESCRIPTION_LINE_CLAMP__,
	__DEFAULT_FORM_DESCRIPTION_LINE_HEIGHT__
};
