import {
	__DEFAULT_STEP_INDEX__,
	__DEFAULT_STEP_IS_ACTIVE__,
	__DEFAULT_STEP_IS_COMPACT__,
	__DEFAULT_STEP_IS_DISABLED__,
	__DEFAULT_STEP_IS_UPPERCASE__,
	__DEFAULT_STEP_STATUS__
} from './props';
import { __DEFAULT_STEP_BORDER_WIDTH__ } from './sizes';

export {
	__DEFAULT_STEP_BORDER_WIDTH__,
	__DEFAULT_STEP_INDEX__,
	__DEFAULT_STEP_IS_ACTIVE__,
	__DEFAULT_STEP_IS_COMPACT__,
	__DEFAULT_STEP_IS_DISABLED__,
	__DEFAULT_STEP_IS_UPPERCASE__,
	__DEFAULT_STEP_STATUS__
};
