import {
	__DEFAULT_CAROUSEL_OVERLAY_ARROW_ICON_BUTTON_AS__,
	__DEFAULT_CAROUSEL_OVERLAY_ARROW_ICON_BUTTON_IS_VISIBLE__
} from './props';

export { __DEFAULT_CAROUSEL_OVERLAY_ARROW_ICON_BUTTON_AS__, __DEFAULT_CAROUSEL_OVERLAY_ARROW_ICON_BUTTON_IS_VISIBLE__ };
