import {
	__DEFAULT_FORM_LABEL_ALIGN__,
	__DEFAULT_FORM_LABEL_AS__,
	__DEFAULT_FORM_LABEL_FONT_WEIGHT__,
	__DEFAULT_FORM_LABEL_LINE_CLAMP__,
	__DEFAULT_FORM_LABEL_LINE_HEIGHT__,
	__DEFAULT_FORM_LABEL_TEXT_TRANSFORM__
} from './props';

export {
	__DEFAULT_FORM_LABEL_ALIGN__,
	__DEFAULT_FORM_LABEL_AS__,
	__DEFAULT_FORM_LABEL_FONT_WEIGHT__,
	__DEFAULT_FORM_LABEL_LINE_CLAMP__,
	__DEFAULT_FORM_LABEL_LINE_HEIGHT__,
	__DEFAULT_FORM_LABEL_TEXT_TRANSFORM__
};
