import { v4 as uuid } from 'uuid';

import type { ResizeClass } from '@common/types';

import {
	DEFAULT_FORMS_IS_COMPACT,
	DEFAULT_FORMS_IS_DISABLED,
	DEFAULT_FORMS_IS_ERROR,
	DEFAULT_FORMS_IS_FOCUSED,
	DEFAULT_FORMS_IS_FULLWIDTH,
	DEFAULT_FORMS_IS_OUTLINED,
	DEFAULT_FORMS_IS_READONLY,
	DEFAULT_FORMS_IS_REQUIRED,
	DEFAULT_FORMS_IS_SUCCESS,
	DEFAULT_FORMS_IS_WARNING,
	DEFAULT_FORMS_SIZE,
	DEFAULT_FORMS_VARIANT
} from '@components/Forms/common/constants';

import type { TextareaDefaultElement, TextareaSize, TextareaVariant } from '../types';

export const DEFAULT_TEXTAREA_AS: TextareaDefaultElement = 'textarea';

export const DEFAULT_TEXTAREA_ID = uuid();

export const DEFAULT_TEXTAREA_IS_COMPACT = DEFAULT_FORMS_IS_COMPACT;
export const DEFAULT_TEXTAREA_IS_DISABLED = DEFAULT_FORMS_IS_DISABLED;
export const DEFAULT_TEXTAREA_IS_FULLWIDTH = DEFAULT_FORMS_IS_FULLWIDTH;
export const DEFAULT_TEXTAREA_IS_ERROR = DEFAULT_FORMS_IS_ERROR;
export const DEFAULT_TEXTAREA_IS_FOCUSED = DEFAULT_FORMS_IS_FOCUSED;
export const DEFAULT_TEXTAREA_IS_OUTLINED = DEFAULT_FORMS_IS_OUTLINED;
export const DEFAULT_TEXTAREA_IS_READONLY = DEFAULT_FORMS_IS_READONLY;
export const DEFAULT_TEXTAREA_IS_REQUIRED = DEFAULT_FORMS_IS_REQUIRED;
export const DEFAULT_TEXTAREA_IS_SUCCESS = DEFAULT_FORMS_IS_SUCCESS;
export const DEFAULT_TEXTAREA_IS_WARNING = DEFAULT_FORMS_IS_WARNING;

export const DEFAULT_TEXTAREA_RESIZE: ResizeClass = 'none';

export const DEFAULT_TEXTAREA_SIZE: TextareaSize = DEFAULT_FORMS_SIZE;

export const DEFAULT_TEXTAREA_VARIANT: TextareaVariant = DEFAULT_FORMS_VARIANT;
