import {
	__DEFAULT_CONTAINER_CENTER_CONTENT__,
	__DEFAULT_CONTAINER_IS_FLUID__,
	__DEFAULT_CONTAINER_SIZE__
} from './props';

export { __DEFAULT_CONTAINER_CENTER_CONTENT__, __DEFAULT_CONTAINER_IS_FLUID__, __DEFAULT_CONTAINER_SIZE__ };
