import { __DEFAULT_SPINNER_IS_VISIBLE__, __DEFAULT_SPINNER_SIZE__, __DEFAULT_SPINNER_VARIANT__ } from './props';

export { __DEFAULT_SPINNER_IS_VISIBLE__, __DEFAULT_SPINNER_SIZE__, __DEFAULT_SPINNER_VARIANT__ };
