import {
	__DEFAULT_FORM_HEADER_ALIGN_CONTENT__,
	__DEFAULT_FORM_HEADER_ALIGN_ITEMS__,
	__DEFAULT_FORM_HEADER_JUSTIFY_CONTENT__,
	__DEFAULT_FORM_HEADER_JUSTIFY_ITEMS__
} from './props';

export {
	__DEFAULT_FORM_HEADER_ALIGN_CONTENT__,
	__DEFAULT_FORM_HEADER_ALIGN_ITEMS__,
	__DEFAULT_FORM_HEADER_JUSTIFY_CONTENT__,
	__DEFAULT_FORM_HEADER_JUSTIFY_ITEMS__
};
