import { __DEFAULT_BADGE_CLOSE_ICON_BUTTON_IS_COMPACT__, __DEFAULT_BADGE_CLOSE_ICON_BUTTON_SIZE__ } from './props';

export { __DEFAULT_BADGE_CLOSE_ICON_BUTTON_IS_COMPACT__, __DEFAULT_BADGE_CLOSE_ICON_BUTTON_SIZE__ };
