import {
	__DEFAULT_SKELETON_IS_ANIMATED__,
	__DEFAULT_SKELETON_IS_LOADED__,
	__DEFAULT_SKELETON_VARIANT__
} from './props';

export { __DEFAULT_SKELETON_IS_ANIMATED__, __DEFAULT_SKELETON_IS_LOADED__, __DEFAULT_SKELETON_VARIANT__ };
