import {
	__DEFAULT_CAROUSEL_AS__,
	__DEFAULT_CAROUSEL_DURATION_NUMBER__,
	__DEFAULT_CAROUSEL_DURATION_THEME__,
	__DEFAULT_CAROUSEL_ID__,
	__DEFAULT_CAROUSEL_ITEMS__,
	__DEFAULT_CAROUSEL_ORIENTTATION__,
	__DEFAULT_CAROUSEL_SCROLL_AMOUNT__,
	__DEFAULT_CAROUSEL_VARIANT__,
	__DEFAULT_CAROUSEL_VISIBLE_ITEMS__
} from './props';

export {
	__DEFAULT_CAROUSEL_AS__,
	__DEFAULT_CAROUSEL_DURATION_NUMBER__,
	__DEFAULT_CAROUSEL_DURATION_THEME__,
	__DEFAULT_CAROUSEL_ID__,
	__DEFAULT_CAROUSEL_ITEMS__,
	__DEFAULT_CAROUSEL_ORIENTTATION__,
	__DEFAULT_CAROUSEL_SCROLL_AMOUNT__,
	__DEFAULT_CAROUSEL_VARIANT__,
	__DEFAULT_CAROUSEL_VISIBLE_ITEMS__
};
