import type { DisplayClassObj, ObjectFitClassObj, ObjectPositionClassObj, OverflowClassObj, PositionClassObj, ThemeAspectRatioObj, ThemeBreakpointObj, ThemeSpacingObj, ZIndexClassObj } from '@common/types';
declare const _default: {
    aspect_ratio: ThemeAspectRatioObj;
    container: ThemeBreakpointObj;
    display: {
        hover: DisplayClassObj;
        focus: DisplayClassObj;
        focus_visible: DisplayClassObj;
        active: DisplayClassObj;
        before: DisplayClassObj;
        after: DisplayClassObj;
        table: string;
        hidden: string;
        container: string;
        flex: string;
        grid: string;
        outline: string;
        inline: string;
        block: string;
        contents: string;
        "flow-root": string;
        "table-caption": string;
        "table-cell": string;
        "table-column": string;
        "table-column-group": string;
        "table-footer-group": string;
        "table-header-group": string;
        "table-row": string;
        "table-row-group": string;
        "inline-block": string;
        "inline-flex": string;
        "inline-grid": string;
        "inline-table": string;
        "list-item": string;
    };
    position: {
        before: PositionClassObj;
        after: PositionClassObj;
        fixed: string;
        sticky: string;
        absolute: string;
        relative: string;
        static: string;
    };
    top: {
        before: ThemeSpacingObj;
        after: ThemeSpacingObj;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        0.25: string;
        0.5: string;
        0.75: string;
        1.25: string;
        1.5: string;
        1.75: string;
        2.25: string;
        2.5: string;
        2.75: string;
        3.25: string;
        3.5: string;
        3.75: string;
        4.25: string;
        4.5: string;
        4.75: string;
        5.25: string;
        5.5: string;
        5.75: string;
        6.25: string;
        6.5: string;
        6.75: string;
        7: string;
        7.25: string;
        7.5: string;
        7.75: string;
        8: string;
        8.25: string;
        8.5: string;
        8.75: string;
        9: string;
        9.25: string;
        9.5: string;
        9.75: string;
        10: string;
        10.25: string;
        10.5: string;
        10.75: string;
        11: string;
        11.25: string;
        11.5: string;
        11.75: string;
        12: string;
        12.25: string;
        12.5: string;
        12.75: string;
        13: string;
        13.25: string;
        13.5: string;
        13.75: string;
        14: string;
        14.25: string;
        14.5: string;
        14.75: string;
        15: string;
        15.25: string;
        15.5: string;
        15.75: string;
        16: string;
        16.25: string;
        16.5: string;
        16.75: string;
        17: string;
        17.25: string;
        17.5: string;
        17.75: string;
        18: string;
        18.25: string;
        18.5: string;
        18.75: string;
        19: string;
        19.25: string;
        19.5: string;
        19.75: string;
        20: string;
        20.25: string;
        20.5: string;
        20.75: string;
        21: string;
        21.25: string;
        21.5: string;
        21.75: string;
        22: string;
        22.25: string;
        22.5: string;
        22.75: string;
        23: string;
        23.25: string;
        23.5: string;
        23.75: string;
        24: string;
        24.25: string;
        24.5: string;
        24.75: string;
    };
    right: {
        before: ThemeSpacingObj;
        after: ThemeSpacingObj;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        0.25: string;
        0.5: string;
        0.75: string;
        1.25: string;
        1.5: string;
        1.75: string;
        2.25: string;
        2.5: string;
        2.75: string;
        3.25: string;
        3.5: string;
        3.75: string;
        4.25: string;
        4.5: string;
        4.75: string;
        5.25: string;
        5.5: string;
        5.75: string;
        6.25: string;
        6.5: string;
        6.75: string;
        7: string;
        7.25: string;
        7.5: string;
        7.75: string;
        8: string;
        8.25: string;
        8.5: string;
        8.75: string;
        9: string;
        9.25: string;
        9.5: string;
        9.75: string;
        10: string;
        10.25: string;
        10.5: string;
        10.75: string;
        11: string;
        11.25: string;
        11.5: string;
        11.75: string;
        12: string;
        12.25: string;
        12.5: string;
        12.75: string;
        13: string;
        13.25: string;
        13.5: string;
        13.75: string;
        14: string;
        14.25: string;
        14.5: string;
        14.75: string;
        15: string;
        15.25: string;
        15.5: string;
        15.75: string;
        16: string;
        16.25: string;
        16.5: string;
        16.75: string;
        17: string;
        17.25: string;
        17.5: string;
        17.75: string;
        18: string;
        18.25: string;
        18.5: string;
        18.75: string;
        19: string;
        19.25: string;
        19.5: string;
        19.75: string;
        20: string;
        20.25: string;
        20.5: string;
        20.75: string;
        21: string;
        21.25: string;
        21.5: string;
        21.75: string;
        22: string;
        22.25: string;
        22.5: string;
        22.75: string;
        23: string;
        23.25: string;
        23.5: string;
        23.75: string;
        24: string;
        24.25: string;
        24.5: string;
        24.75: string;
    };
    bottom: {
        before: ThemeSpacingObj;
        after: ThemeSpacingObj;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        0.25: string;
        0.5: string;
        0.75: string;
        1.25: string;
        1.5: string;
        1.75: string;
        2.25: string;
        2.5: string;
        2.75: string;
        3.25: string;
        3.5: string;
        3.75: string;
        4.25: string;
        4.5: string;
        4.75: string;
        5.25: string;
        5.5: string;
        5.75: string;
        6.25: string;
        6.5: string;
        6.75: string;
        7: string;
        7.25: string;
        7.5: string;
        7.75: string;
        8: string;
        8.25: string;
        8.5: string;
        8.75: string;
        9: string;
        9.25: string;
        9.5: string;
        9.75: string;
        10: string;
        10.25: string;
        10.5: string;
        10.75: string;
        11: string;
        11.25: string;
        11.5: string;
        11.75: string;
        12: string;
        12.25: string;
        12.5: string;
        12.75: string;
        13: string;
        13.25: string;
        13.5: string;
        13.75: string;
        14: string;
        14.25: string;
        14.5: string;
        14.75: string;
        15: string;
        15.25: string;
        15.5: string;
        15.75: string;
        16: string;
        16.25: string;
        16.5: string;
        16.75: string;
        17: string;
        17.25: string;
        17.5: string;
        17.75: string;
        18: string;
        18.25: string;
        18.5: string;
        18.75: string;
        19: string;
        19.25: string;
        19.5: string;
        19.75: string;
        20: string;
        20.25: string;
        20.5: string;
        20.75: string;
        21: string;
        21.25: string;
        21.5: string;
        21.75: string;
        22: string;
        22.25: string;
        22.5: string;
        22.75: string;
        23: string;
        23.25: string;
        23.5: string;
        23.75: string;
        24: string;
        24.25: string;
        24.5: string;
        24.75: string;
    };
    left: {
        before: ThemeSpacingObj;
        after: ThemeSpacingObj;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        0.25: string;
        0.5: string;
        0.75: string;
        1.25: string;
        1.5: string;
        1.75: string;
        2.25: string;
        2.5: string;
        2.75: string;
        3.25: string;
        3.5: string;
        3.75: string;
        4.25: string;
        4.5: string;
        4.75: string;
        5.25: string;
        5.5: string;
        5.75: string;
        6.25: string;
        6.5: string;
        6.75: string;
        7: string;
        7.25: string;
        7.5: string;
        7.75: string;
        8: string;
        8.25: string;
        8.5: string;
        8.75: string;
        9: string;
        9.25: string;
        9.5: string;
        9.75: string;
        10: string;
        10.25: string;
        10.5: string;
        10.75: string;
        11: string;
        11.25: string;
        11.5: string;
        11.75: string;
        12: string;
        12.25: string;
        12.5: string;
        12.75: string;
        13: string;
        13.25: string;
        13.5: string;
        13.75: string;
        14: string;
        14.25: string;
        14.5: string;
        14.75: string;
        15: string;
        15.25: string;
        15.5: string;
        15.75: string;
        16: string;
        16.25: string;
        16.5: string;
        16.75: string;
        17: string;
        17.25: string;
        17.5: string;
        17.75: string;
        18: string;
        18.25: string;
        18.5: string;
        18.75: string;
        19: string;
        19.25: string;
        19.5: string;
        19.75: string;
        20: string;
        20.25: string;
        20.5: string;
        20.75: string;
        21: string;
        21.25: string;
        21.5: string;
        21.75: string;
        22: string;
        22.25: string;
        22.5: string;
        22.75: string;
        23: string;
        23.25: string;
        23.5: string;
        23.75: string;
        24: string;
        24.25: string;
        24.5: string;
        24.75: string;
    };
    object_fit: ObjectFitClassObj;
    object_position: ObjectPositionClassObj;
    overflow: OverflowClassObj;
    overflow_x: OverflowClassObj;
    overflow_y: OverflowClassObj;
    z_index: {
        before: ZIndexClassObj;
        after: ZIndexClassObj;
        0: string | number;
        auto: string | number;
        1: string | number;
        2: string | number;
        3: string | number;
        4: string | number;
        5: string | number;
        6: string | number;
        7: string | number;
        8: string | number;
        9: string | number;
        10: string | number;
        11: string | number;
        12: string | number;
        13: string | number;
        14: string | number;
        15: string | number;
        16: string | number;
        17: string | number;
        18: string | number;
        19: string | number;
        20: string | number;
        21: string | number;
        22: string | number;
        23: string | number;
        24: string | number;
        banner: string | number;
        tooltip: string | number;
        50: string | number;
        75: string | number;
        100: string | number;
        30: string | number;
        overlay: string | number;
        25: string | number;
        40: string | number;
        250: string | number;
        500: string | number;
        1000: string | number;
        dropdown: string | number;
        sticky: string | number;
        modal: string | number;
        popover: string | number;
        skipLink: string | number;
        toast: string | number;
    };
};
export default _default;
//# sourceMappingURL=layout.d.ts.map