import {
	__DEFAULT_FILE_BUTTON_ACCEPT__,
	__DEFAULT_FILE_BUTTON_DURATION__,
	__DEFAULT_FILE_BUTTON_IS_MULTIPLE__,
	__DEFAULT_FILE_BUTTON_TIMEOUT__
} from './props';

export {
	__DEFAULT_FILE_BUTTON_ACCEPT__,
	__DEFAULT_FILE_BUTTON_DURATION__,
	__DEFAULT_FILE_BUTTON_IS_MULTIPLE__,
	__DEFAULT_FILE_BUTTON_TIMEOUT__
};
