import {
	__DEFAULT_DELETE_ICON_BUTTON_HAS_TOOLTIP__,
	__DEFAULT_DELETE_ICON_BUTTON_LABEL__,
	__DEFAULT_DELETE_ICON_BUTTON_PLACEMENT__
} from './props';

export {
	__DEFAULT_DELETE_ICON_BUTTON_HAS_TOOLTIP__,
	__DEFAULT_DELETE_ICON_BUTTON_LABEL__,
	__DEFAULT_DELETE_ICON_BUTTON_PLACEMENT__
};
