import * as commonConstants from './common/constants';
import {
	useGetHorizontalScrollAPIContext,
	useHorizontalScrollArrowState,
	useHorizontalScrollContext,
	useSetHorizontalScrollAPIContext
} from './common/hooks';
import * as commonKeys from './common/keys';
import type {
	HorizontalScrollAPIContext,
	HorizontalScrollArrowDirection,
	HorizontalScrollArrowSize,
	HorizontalScrollContext,
	HorizontalScrollProps,
	HorizontalScrollRef,
	HorizontalScrollVariant
} from './common/types';
import type {
	HorizontalScrollArrowIconButtonDefaultElement,
	HorizontalScrollArrowIconButtonElement,
	HorizontalScrollArrowIconButtonGroupProps,
	HorizontalScrollArrowIconButtonGroupRef,
	HorizontalScrollArrowIconButtonProps,
	HorizontalScrollArrowIconButtonRef,
	HorizontalScrollItemProps,
	HorizontalScrollItemRef,
	HorizontalScrollLeftArrowIconButtonDefaultElement,
	HorizontalScrollLeftArrowIconButtonElement,
	HorizontalScrollLeftArrowIconButtonProps,
	HorizontalScrollLeftArrowIconButtonRef,
	HorizontalScrollLeftArrowIconButtonScrollAmount,
	HorizontalScrollLeftLinearGradientProps,
	HorizontalScrollLeftLinearGradientRef,
	HorizontalScrollLinearGradientProps,
	HorizontalScrollLinearGradientRef,
	HorizontalScrollOverlayArrowIconButtonDefaultElement,
	HorizontalScrollOverlayArrowIconButtonElement,
	HorizontalScrollOverlayArrowIconButtonProps,
	HorizontalScrollOverlayArrowIconButtonRef,
	HorizontalScrollOverlayLeftArrowIconButtonDefaultElement,
	HorizontalScrollOverlayLeftArrowIconButtonElement,
	HorizontalScrollOverlayLeftArrowIconButtonProps,
	HorizontalScrollOverlayLeftArrowIconButtonRef,
	HorizontalScrollOverlayLeftArrowIconButtonScrollAmount,
	HorizontalScrollOverlayRightArrowIconButtonDefaultElement,
	HorizontalScrollOverlayRightArrowIconButtonElement,
	HorizontalScrollOverlayRightArrowIconButtonProps,
	HorizontalScrollOverlayRightArrowIconButtonRef,
	HorizontalScrollOverlayRightArrowIconButtonScrollAmount,
	HorizontalScrollRightArrowIconButtonDefaultElement,
	HorizontalScrollRightArrowIconButtonElement,
	HorizontalScrollRightArrowIconButtonProps,
	HorizontalScrollRightArrowIconButtonRef,
	HorizontalScrollRightArrowIconButtonScrollAmount,
	HorizontalScrollRightLinearGradientProps,
	HorizontalScrollRightLinearGradientRef
} from './components';
import {
	constants as componentsConstants,
	HorizontalScrollArrowIconButton,
	HorizontalScrollArrowIconButtonGroup,
	HorizontalScrollItem,
	HorizontalScrollLeftArrowIconButton,
	HorizontalScrollLeftLinearGradient,
	HorizontalScrollLinearGradient,
	HorizontalScrollOverlayArrowIconButton,
	HorizontalScrollOverlayLeftArrowIconButton,
	HorizontalScrollOverlayRightArrowIconButton,
	HorizontalScrollRightArrowIconButton,
	HorizontalScrollRightLinearGradient,
	keys as componentsKeys
} from './components';
import HorizontalScroll from './HorizontalScroll';

// Constants
export const constants = {
	...commonConstants,
	...componentsConstants
};

// Keys
export const keys = {
	...commonKeys,
	...componentsKeys
};

// Hooks
export {
	useGetHorizontalScrollAPIContext,
	useHorizontalScrollArrowState,
	useHorizontalScrollContext,
	useSetHorizontalScrollAPIContext
};

// Components
export {
	HorizontalScroll,
	HorizontalScrollArrowIconButton,
	HorizontalScrollArrowIconButtonGroup,
	HorizontalScrollItem,
	HorizontalScrollLeftArrowIconButton,
	HorizontalScrollLeftLinearGradient,
	HorizontalScrollLinearGradient,
	HorizontalScrollOverlayArrowIconButton,
	HorizontalScrollOverlayLeftArrowIconButton,
	HorizontalScrollOverlayRightArrowIconButton,
	HorizontalScrollRightArrowIconButton,
	HorizontalScrollRightLinearGradient
};

// Component Types
export type {
	HorizontalScrollAPIContext,
	HorizontalScrollArrowDirection,
	HorizontalScrollArrowIconButtonDefaultElement,
	HorizontalScrollArrowIconButtonElement,
	HorizontalScrollArrowIconButtonGroupProps,
	HorizontalScrollArrowIconButtonGroupRef,
	HorizontalScrollArrowIconButtonProps,
	HorizontalScrollArrowIconButtonRef,
	HorizontalScrollArrowSize,
	HorizontalScrollContext,
	HorizontalScrollItemProps,
	HorizontalScrollItemRef,
	HorizontalScrollLeftArrowIconButtonDefaultElement,
	HorizontalScrollLeftArrowIconButtonElement,
	HorizontalScrollLeftArrowIconButtonProps,
	HorizontalScrollLeftArrowIconButtonRef,
	HorizontalScrollLeftArrowIconButtonScrollAmount,
	HorizontalScrollLeftLinearGradientProps,
	HorizontalScrollLeftLinearGradientRef,
	HorizontalScrollLinearGradientProps,
	HorizontalScrollLinearGradientRef,
	HorizontalScrollOverlayArrowIconButtonDefaultElement,
	HorizontalScrollOverlayArrowIconButtonElement,
	HorizontalScrollOverlayArrowIconButtonProps,
	HorizontalScrollOverlayArrowIconButtonRef,
	HorizontalScrollOverlayLeftArrowIconButtonDefaultElement,
	HorizontalScrollOverlayLeftArrowIconButtonElement,
	HorizontalScrollOverlayLeftArrowIconButtonProps,
	HorizontalScrollOverlayLeftArrowIconButtonRef,
	HorizontalScrollOverlayLeftArrowIconButtonScrollAmount,
	HorizontalScrollOverlayRightArrowIconButtonDefaultElement,
	HorizontalScrollOverlayRightArrowIconButtonElement,
	HorizontalScrollOverlayRightArrowIconButtonProps,
	HorizontalScrollOverlayRightArrowIconButtonRef,
	HorizontalScrollOverlayRightArrowIconButtonScrollAmount,
	HorizontalScrollProps,
	HorizontalScrollRef,
	HorizontalScrollRightArrowIconButtonDefaultElement,
	HorizontalScrollRightArrowIconButtonElement,
	HorizontalScrollRightArrowIconButtonProps,
	HorizontalScrollRightArrowIconButtonRef,
	HorizontalScrollRightArrowIconButtonScrollAmount,
	HorizontalScrollRightLinearGradientProps,
	HorizontalScrollRightLinearGradientRef,
	HorizontalScrollVariant
};
