import {
	__DEFAULT_LINEAR_GRADIENT_COLOR__,
	__DEFAULT_LINEAR_GRADIENT_DIRECTION__,
	__DEFAULT_LINEAR_GRADIENT_FROM_POS__,
	__DEFAULT_LINEAR_GRADIENT_MIDDLE_POS__,
	__DEFAULT_LINEAR_GRADIENT_TO_POS__
} from './props';

export {
	__DEFAULT_LINEAR_GRADIENT_COLOR__,
	__DEFAULT_LINEAR_GRADIENT_DIRECTION__,
	__DEFAULT_LINEAR_GRADIENT_FROM_POS__,
	__DEFAULT_LINEAR_GRADIENT_MIDDLE_POS__,
	__DEFAULT_LINEAR_GRADIENT_TO_POS__
};
