import {
	__DEFAULT_SWITCH_HAS_IO_LABEL__,
	__DEFAULT_SWITCH_ID__,
	__DEFAULT_SWITCH_IS_ACTIVE__,
	__DEFAULT_SWITCH_IS_CHECKED__,
	__DEFAULT_SWITCH_IS_CLICKABLE__,
	__DEFAULT_SWITCH_IS_COMPACT__,
	__DEFAULT_SWITCH_IS_DISABLED__,
	__DEFAULT_SWITCH_IS_ERROR__,
	__DEFAULT_SWITCH_IS_FOCUSED__,
	__DEFAULT_SWITCH_IS_OUTLINED__,
	__DEFAULT_SWITCH_IS_READONLY__,
	__DEFAULT_SWITCH_IS_REQUIRED__,
	__DEFAULT_SWITCH_IS_SUCCESS__,
	__DEFAULT_SWITCH_IS_WARNING__,
	__DEFAULT_SWITCH_LABEL_POSITION__,
	__DEFAULT_SWITCH_SIZE__,
	__DEFAULT_SWITCH_TYPE__
} from './props';
import { __DEFAULT_SWITCH_LINE_HEIGHT_SIZE__ } from './sizes';

export {
	__DEFAULT_SWITCH_HAS_IO_LABEL__,
	__DEFAULT_SWITCH_ID__,
	__DEFAULT_SWITCH_IS_ACTIVE__,
	__DEFAULT_SWITCH_IS_CHECKED__,
	__DEFAULT_SWITCH_IS_CLICKABLE__,
	__DEFAULT_SWITCH_IS_COMPACT__,
	__DEFAULT_SWITCH_IS_DISABLED__,
	__DEFAULT_SWITCH_IS_ERROR__,
	__DEFAULT_SWITCH_IS_FOCUSED__,
	__DEFAULT_SWITCH_IS_OUTLINED__,
	__DEFAULT_SWITCH_IS_READONLY__,
	__DEFAULT_SWITCH_IS_REQUIRED__,
	__DEFAULT_SWITCH_IS_SUCCESS__,
	__DEFAULT_SWITCH_IS_WARNING__,
	__DEFAULT_SWITCH_LABEL_POSITION__,
	__DEFAULT_SWITCH_LINE_HEIGHT_SIZE__,
	__DEFAULT_SWITCH_SIZE__,
	__DEFAULT_SWITCH_TYPE__
};
