import type { ComponentProps } from 'react';

import { v4 as uuid } from 'uuid';

import {
	DEFAULT_FORMS_IS_COMPACT,
	DEFAULT_FORMS_IS_DISABLED,
	DEFAULT_FORMS_IS_ERROR,
	DEFAULT_FORMS_IS_FOCUSED,
	DEFAULT_FORMS_IS_OUTLINED,
	DEFAULT_FORMS_IS_READONLY,
	DEFAULT_FORMS_IS_REQUIRED,
	DEFAULT_FORMS_IS_SUCCESS,
	DEFAULT_FORMS_IS_WARNING,
	DEFAULT_FORMS_SIZE
} from '@components/Forms/common/constants';

import type { SwitchLabelPosition, SwitchSize } from '../types';

export const DEFAULT_SWITCH_HAS_IO_LABEL = true;

export const DEFAULT_SWITCH_ID = uuid();

export const DEFAULT_SWITCH_IS_ACTIVE = false;
export const DEFAULT_SWITCH_IS_CHECKED = false;
export const DEFAULT_SWITCH_IS_CLICKABLE = true;
export const DEFAULT_SWITCH_IS_COMPACT = DEFAULT_FORMS_IS_COMPACT;
export const DEFAULT_SWITCH_IS_DISABLED = DEFAULT_FORMS_IS_DISABLED;
export const DEFAULT_SWITCH_IS_ERROR = DEFAULT_FORMS_IS_ERROR;
export const DEFAULT_SWITCH_IS_FOCUSED = DEFAULT_FORMS_IS_FOCUSED;
export const DEFAULT_SWITCH_IS_OUTLINED = DEFAULT_FORMS_IS_OUTLINED;
export const DEFAULT_SWITCH_IS_READONLY = DEFAULT_FORMS_IS_READONLY;
export const DEFAULT_SWITCH_IS_REQUIRED = DEFAULT_FORMS_IS_REQUIRED;
export const DEFAULT_SWITCH_IS_SUCCESS = DEFAULT_FORMS_IS_SUCCESS;
export const DEFAULT_SWITCH_IS_WARNING = DEFAULT_FORMS_IS_WARNING;

export const DEFAULT_SWITCH_LABEL_POSITION: SwitchLabelPosition = 'right';

export const DEFAULT_SWITCH_TYPE: ComponentProps<'input'>['type'] = 'switch';

export const DEFAULT_SWITCH_SIZE: SwitchSize = DEFAULT_FORMS_SIZE;
