import { __DEFAULT_HORIZONTAL_SCROLL_ARROW_SIZE__, __DEFAULT_HORIZONTAL_SCROLL_VARIANT__ } from './props';

export { __DEFAULT_HORIZONTAL_SCROLL_ARROW_SIZE__, __DEFAULT_HORIZONTAL_SCROLL_VARIANT__ };
