import { __DEFAULT_DUMMY_ICON_BUTTON_ICON_AS__, __DEFAULT_DUMMY_ICON_BUTTON_ICON_VARIANT__ } from './props';

export { __DEFAULT_DUMMY_ICON_BUTTON_ICON_AS__, __DEFAULT_DUMMY_ICON_BUTTON_ICON_VARIANT__ };
