import {
	__DEFAULT_STACK_ALIGNITEMS__,
	__DEFAULT_STACK_DIRECTION__,
	__DEFAULT_STACK_JUSTIFYCONTENT__,
	__DEFAULT_STACK_WRAP__
} from './props';

export {
	__DEFAULT_STACK_ALIGNITEMS__,
	__DEFAULT_STACK_DIRECTION__,
	__DEFAULT_STACK_JUSTIFYCONTENT__,
	__DEFAULT_STACK_WRAP__
};
