import {
	__DEFAULT_CAROUSEL_ARROW_BUTTON_GROUP_IS_ATTACHED__,
	__DEFAULT_CAROUSEL_ARROW_BUTTON_GROUP_IS_FULLWIDTH__
} from './props';

export { __DEFAULT_CAROUSEL_ARROW_BUTTON_GROUP_IS_ATTACHED__, __DEFAULT_CAROUSEL_ARROW_BUTTON_GROUP_IS_FULLWIDTH__ };
