import {
	__DEFAULT_AMOUNT_ACTIVE__,
	__DEFAULT_AMOUNT_BACK__,
	__DEFAULT_AMOUNT_HOVER__,
	__DEFAULT_AMOUNT_PLACEHOLDER__,
	__DEFAULT_AMOUNT_SELECTION__
} from './amount';
import { __DEFAULT_POLYMORPHIC_ELEMENT__, __DEFAULT_POLYMORPHIC_OBJECT__ } from './polymorphic';
import {
	__DEFAULT_APP_COLOR__,
	__DEFAULT_APP_COLORMODE__,
	__DEFAULT_HAS_FILLEDICON_LOADED__,
	__DEFAULT_HAS_OUTLINEDICON_LOADED__,
	__DEFAULT_HAS_TWOTONEICON_LOADED__,
	__DEFAULT_METHOD__
} from './props';

export {
	__DEFAULT_AMOUNT_ACTIVE__,
	__DEFAULT_AMOUNT_BACK__,
	__DEFAULT_AMOUNT_HOVER__,
	__DEFAULT_AMOUNT_PLACEHOLDER__,
	__DEFAULT_AMOUNT_SELECTION__,
	__DEFAULT_APP_COLOR__,
	__DEFAULT_APP_COLORMODE__,
	__DEFAULT_HAS_FILLEDICON_LOADED__,
	__DEFAULT_HAS_OUTLINEDICON_LOADED__,
	__DEFAULT_HAS_TWOTONEICON_LOADED__,
	__DEFAULT_METHOD__,
	__DEFAULT_POLYMORPHIC_ELEMENT__,
	__DEFAULT_POLYMORPHIC_OBJECT__
};
