import {
	__DEFAULT_CONTAINER_BREAKPOINT__,
	__DEFAULT_CONTAINER_IS_CONTENT_CENTERED__,
	__DEFAULT_CONTAINER_IS_FLUID__
} from './props';

export { __DEFAULT_CONTAINER_BREAKPOINT__, __DEFAULT_CONTAINER_IS_CONTENT_CENTERED__, __DEFAULT_CONTAINER_IS_FLUID__ };
