import {
	__DEFAULT_CONTAINER_IS_CONTENT_CENTERED__,
	__DEFAULT_CONTAINER_IS_FLUID__,
	__DEFAULT_CONTAINER_SIZE__
} from './props';

export { __DEFAULT_CONTAINER_IS_CONTENT_CENTERED__, __DEFAULT_CONTAINER_IS_FLUID__, __DEFAULT_CONTAINER_SIZE__ };
