import { __DEFAULT_SLIDE_IS_REVERSED__, __DEFAULT_SLIDE_OFFSET_X__, __DEFAULT_SLIDE_OFFSET_Y__ } from './props';

export { __DEFAULT_SLIDE_IS_REVERSED__, __DEFAULT_SLIDE_OFFSET_X__, __DEFAULT_SLIDE_OFFSET_Y__ };
