/// <reference types="react" />
import type { CarouselArrowButtonDefaultElement, CarouselArrowButtonElement, CarouselArrowButtonMouseEvent, CarouselArrowButtonProps, CarouselArrowButtonRef } from './CarouselArrowButton';
import { CarouselArrowButton } from './CarouselArrowButton';
import type { CarouselArrowButtonGroupProps, CarouselArrowButtonGroupRef } from './CarouselArrowButtonGroup';
import { CarouselArrowButtonGroup } from './CarouselArrowButtonGroup';
import type { CarouselArrowIconButtonDefaultElement, CarouselArrowIconButtonElement, CarouselArrowIconButtonMouseEvent, CarouselArrowIconButtonProps, CarouselArrowIconButtonRef } from './CarouselArrowIconButton';
import { CarouselArrowIconButton } from './CarouselArrowIconButton';
import type { CarouselArrowIconButtonGroupProps, CarouselArrowIconButtonGroupRef } from './CarouselArrowIconButtonGroup';
import { CarouselArrowIconButtonGroup } from './CarouselArrowIconButtonGroup';
import type { CarouselDotProps, CarouselDotRef, CarouselDotsProps, CarouselDotsRef, CarouselDotsType, CarouselDotType } from './CarouselDots';
import { CarouselDots } from './CarouselDots';
import type { CarouselItemProps, CarouselItemRef } from './CarouselItem';
import { CarouselItem } from './CarouselItem';
import type { CarouselLeftArrowButtonDefaultElement, CarouselLeftArrowButtonElement, CarouselLeftArrowButtonProps, CarouselLeftArrowButtonRef } from './CarouselLeftArrowButton';
import { CarouselLeftArrowButton } from './CarouselLeftArrowButton';
import type { CarouselLeftArrowIconButtonDefaultElement, CarouselLeftArrowIconButtonElement, CarouselLeftArrowIconButtonProps, CarouselLeftArrowIconButtonRef } from './CarouselLeftArrowIconButton';
import { CarouselLeftArrowIconButton } from './CarouselLeftArrowIconButton';
import type { CarouselLeftLinearGradientProps, CarouselLeftLinearGradientRef } from './CarouselLeftLinearGradient';
import { CarouselLeftLinearGradient } from './CarouselLeftLinearGradient';
import type { CarouselLinearGradientProps, CarouselLinearGradientRef } from './CarouselLinearGradient';
import { CarouselLinearGradient } from './CarouselLinearGradient';
import type { CarouselOverlayArrowButtonDefaultElement, CarouselOverlayArrowButtonElement, CarouselOverlayArrowButtonProps, CarouselOverlayArrowButtonRef } from './CarouselOverlayArrowButton';
import { CarouselOverlayArrowButton } from './CarouselOverlayArrowButton';
import type { CarouselOverlayArrowIconButtonDefaultElement, CarouselOverlayArrowIconButtonElement, CarouselOverlayArrowIconButtonProps, CarouselOverlayArrowIconButtonRef } from './CarouselOverlayArrowIconButton';
import { CarouselOverlayArrowIconButton } from './CarouselOverlayArrowIconButton';
import type { CarouselOverlayLeftArrowButtonDefaultElement, CarouselOverlayLeftArrowButtonElement, CarouselOverlayLeftArrowButtonProps, CarouselOverlayLeftArrowButtonRef } from './CarouselOverlayLeftArrowButton';
import { CarouselOverlayLeftArrowButton } from './CarouselOverlayLeftArrowButton';
import type { CarouselOverlayLeftArrowIconButtonDefaultElement, CarouselOverlayLeftArrowIconButtonElement, CarouselOverlayLeftArrowIconButtonProps, CarouselOverlayLeftArrowIconButtonRef } from './CarouselOverlayLeftArrowIconButton';
import { CarouselOverlayLeftArrowIconButton } from './CarouselOverlayLeftArrowIconButton';
import type { CarouselOverlayRightArrowButtonDefaultElement, CarouselOverlayRightArrowButtonElement, CarouselOverlayRightArrowButtonProps, CarouselOverlayRightArrowButtonRef } from './CarouselOverlayRightArrowButton';
import { CarouselOverlayRightArrowButton } from './CarouselOverlayRightArrowButton';
import type { CarouselOverlayRightArrowIconButtonDefaultElement, CarouselOverlayRightArrowIconButtonElement, CarouselOverlayRightArrowIconButtonProps, CarouselOverlayRightArrowIconButtonRef } from './CarouselOverlayRightArrowIconButton';
import { CarouselOverlayRightArrowIconButton } from './CarouselOverlayRightArrowIconButton';
import type { CarouselRightArrowButtonDefaultElement, CarouselRightArrowButtonElement, CarouselRightArrowButtonProps, CarouselRightArrowButtonRef } from './CarouselRightArrowButton';
import { CarouselRightArrowButton } from './CarouselRightArrowButton';
import type { CarouselRightArrowIconButtonDefaultElement, CarouselRightArrowIconButtonElement, CarouselRightArrowIconButtonProps, CarouselRightArrowIconButtonRef } from './CarouselRightArrowIconButton';
import { CarouselRightArrowIconButton } from './CarouselRightArrowIconButton';
import type { CarouselRightLinearGradientProps, CarouselRightLinearGradientRef } from './CarouselRightLinearGradient';
import { CarouselRightLinearGradient } from './CarouselRightLinearGradient';
export declare const constants: {
    __DEFAULT_CAROUSEL_DOTS__: CarouselDotsType;
    __DEFAULT_CAROUSEL_DOTS_SIZE__: import("../../../../..").ThemeSpacing;
    __DEFAULT_CAROUSEL_LINEAR_GRADIENT_IS_VISIBLE__: false;
    __DEFAULT_CAROUSEL_OVERLAY_ARROW_ICON_BUTTON_IS_VISIBLE__: false;
    __DEFAULT_CAROUSEL_OVERLAY_ARROW_BUTTON_IS_VISIBLE__: false;
    __DEFAULT_CAROUSEL_ARROW_BUTTON_GROUP_IS_ATTACHED__: true;
    __DEFAULT_CAROUSEL_ARROW_BUTTON_GROUP_IS_FULLWIDTH__: true;
    __DEFAULT_CAROUSEL_ARROW_BUTTON_BOTTOM_LABEL__: "Scroll Bottom";
    __DEFAULT_CAROUSEL_ARROW_BUTTON_HAS_ICON__: true;
    __DEFAULT_CAROUSEL_ARROW_BUTTON_IS_FULLWIDTH__: true;
    __DEFAULT_CAROUSEL_ARROW_BUTTON_LEFT_LABEL__: "Scroll Left";
    __DEFAULT_CAROUSEL_ARROW_BUTTON_RIGHT_LABEL__: "Scroll Right";
    __DEFAULT_CAROUSEL_ARROW_BUTTON_TOP_LABEL__: "Scroll Top";
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_GROUP_IS_ATTACHED__: true;
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_BOTTOM_LABEL__: "Scroll Bottom";
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_HAS_TOOLTIP__: true;
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_LEFT_LABEL__: "Scroll Left";
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_PLACEMENT__: import("../../../../Overlay").TooltipPlacement;
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_RIGHT_LABEL__: "Scroll Right";
    __DEFAULT_CAROUSEL_ARROW_ICON_BUTTON_TOP_LABEL__: "Scroll Top";
};
export declare const keys: {
    __KEYS_CAROUSEL_RIGHT_ARROW_BUTTON_CLASS__: "ds-cl-carousel-right-arrow-button";
    __KEYS_CAROUSEL_OVERLAY_RIGHT_ARROW_BUTTON_CLASS__: "ds-cl-carousel-overlay-right-arrow-button";
    __KEYS_CAROUSEL_OVERLAY_LEFT_ARROW_BUTTON_CLASS__: "ds-cl-carousel-overlay-left-arrow-button";
    __KEYS_CAROUSEL_OVERLAY_ARROW_BUTTON_CLASS__: "ds-cl-carousel-overlay-arrow-button";
    __KEYS_CAROUSEL_LEFT_ARROW_BUTTON_CLASS__: "ds-cl-carousel-left-arrow-button";
    __KEYS_CAROUSEL_DOT_CLASS__: "ds-cl-carousel-dot";
    __KEYS_CAROUSEL_DOTS_CLASS__: "ds-cl-carousel-dots";
    __KEYS_CAROUSEL_ARROW_BUTTON_GROUP_CLASS__: "ds-cl-carousel-arrow-button-group";
    __KEYS_CAROUSEL_ARROW_BUTTON_CLASS__: "ds-cl-carousel-arrow-button";
    __KEYS_CAROUSEL_RIGHT_LINEAR_GRADIENT_CLASS__: "ds-cl-carousel-right-linear-gradient";
    __KEYS_CAROUSEL_RIGHT_ARROW_ICON_BUTTON_CLASS__: "ds-cl-carousel-right-arrow-icon-button";
    __KEYS_CAROUSEL_OVERLAY_RIGHT_ARROW_ICON_BUTTON_CLASS__: "ds-cl-carousel-overlay-right-arrow-icon-button";
    __KEYS_CAROUSEL_OVERLAY_LEFT_ARROW_ICON_BUTTON_CLASS__: "ds-cl-carousel-overlay-left-arrow-icon-button";
    __KEYS_CAROUSEL_OVERLAY_ARROW_ICON_BUTTON_CLASS__: "ds-cl-carousel-overlay-arrow-icon-button";
    __KEYS_CAROUSEL_LINEAR_GRADIENT_CLASS__: "ds-cl-carousel-linear-gradient";
    __KEYS_CAROUSEL_LEFT_LINEAR_GRADIENT_CLASS__: "ds-cl-carousel-left-linear-gradient";
    __KEYS_CAROUSEL_LEFT_ARROW_ICON_BUTTON_CLASS__: "ds-cl-carousel-left-arrow-icon-button";
    __KEYS_CAROUSEL_ITEM_CLASS__: "ds-cl-carousel-item";
    __KEYS_CAROUSEL_ARROW_ICON_BUTTON_GROUP_CLASS__: "ds-cl-carousel-arrow-icon-button-group";
    __KEYS_CAROUSEL_ARROW_ICON_BUTTON_CLASS__: "ds-cl-carousel-arrow-icon-button";
};
export declare const hooks: {
    useCarouselDotClasses: <Element_1 extends import("react").ElementType = "div">(props: Pick<CarouselDotProps<Element_1>, "color" | "size" | "colorMode"> & {
        isVisible: boolean;
    }) => {
        item: string;
        scale100: string;
        scale75: string;
        scale50: string;
    };
};
export { CarouselArrowButton, CarouselArrowButtonGroup, CarouselArrowIconButton, CarouselArrowIconButtonGroup, CarouselDots, CarouselItem, CarouselLeftArrowButton, CarouselLeftArrowIconButton, CarouselLeftLinearGradient, CarouselLinearGradient, CarouselOverlayArrowButton, CarouselOverlayArrowIconButton, CarouselOverlayLeftArrowButton, CarouselOverlayLeftArrowIconButton, CarouselOverlayRightArrowButton, CarouselOverlayRightArrowIconButton, CarouselRightArrowButton, CarouselRightArrowIconButton, CarouselRightLinearGradient };
export type { CarouselArrowButtonDefaultElement, CarouselArrowButtonElement, CarouselArrowButtonGroupProps, CarouselArrowButtonGroupRef, CarouselArrowButtonMouseEvent, CarouselArrowButtonProps, CarouselArrowButtonRef, CarouselArrowIconButtonDefaultElement, CarouselArrowIconButtonElement, CarouselArrowIconButtonGroupProps, CarouselArrowIconButtonGroupRef, CarouselArrowIconButtonMouseEvent, CarouselArrowIconButtonProps, CarouselArrowIconButtonRef, CarouselDotProps, CarouselDotRef, CarouselDotsProps, CarouselDotsRef, CarouselDotsType, CarouselDotType, CarouselItemProps, CarouselItemRef, CarouselLeftArrowButtonDefaultElement, CarouselLeftArrowButtonElement, CarouselLeftArrowButtonProps, CarouselLeftArrowButtonRef, CarouselLeftArrowIconButtonDefaultElement, CarouselLeftArrowIconButtonElement, CarouselLeftArrowIconButtonProps, CarouselLeftArrowIconButtonRef, CarouselLeftLinearGradientProps, CarouselLeftLinearGradientRef, CarouselLinearGradientProps, CarouselLinearGradientRef, CarouselOverlayArrowButtonDefaultElement, CarouselOverlayArrowButtonElement, CarouselOverlayArrowButtonProps, CarouselOverlayArrowButtonRef, CarouselOverlayArrowIconButtonDefaultElement, CarouselOverlayArrowIconButtonElement, CarouselOverlayArrowIconButtonProps, CarouselOverlayArrowIconButtonRef, CarouselOverlayLeftArrowButtonDefaultElement, CarouselOverlayLeftArrowButtonElement, CarouselOverlayLeftArrowButtonProps, CarouselOverlayLeftArrowButtonRef, CarouselOverlayLeftArrowIconButtonDefaultElement, CarouselOverlayLeftArrowIconButtonElement, CarouselOverlayLeftArrowIconButtonProps, CarouselOverlayLeftArrowIconButtonRef, CarouselOverlayRightArrowButtonDefaultElement, CarouselOverlayRightArrowButtonElement, CarouselOverlayRightArrowButtonProps, CarouselOverlayRightArrowButtonRef, CarouselOverlayRightArrowIconButtonDefaultElement, CarouselOverlayRightArrowIconButtonElement, CarouselOverlayRightArrowIconButtonProps, CarouselOverlayRightArrowIconButtonRef, CarouselRightArrowButtonDefaultElement, CarouselRightArrowButtonElement, CarouselRightArrowButtonProps, CarouselRightArrowButtonRef, CarouselRightArrowIconButtonDefaultElement, CarouselRightArrowIconButtonElement, CarouselRightArrowIconButtonProps, CarouselRightArrowIconButtonRef, CarouselRightLinearGradientProps, CarouselRightLinearGradientRef };
//# sourceMappingURL=index.d.ts.map