import * as commonConstants from './common/constants';
import { useCarouselArrowState, useCarouselClasses, useCarouselContext, useCarouselManager } from './common/hooks';
import * as commonKeys from './common/keys';
import type {
	CarouselArrowDirection,
	CarouselContext,
	CarouselItem,
	CarouselItems,
	CarouselOrientation,
	CarouselProps,
	CarouselRef,
	CarouselRenderIconButtonProps,
	CarouselScrollAmount,
	CarouselVariant
} from './common/types';
import * as commonUtils from './common/utils';
import Carousel from './Carousel';
import type {
	CarouselArrowButtonDefaultElement,
	CarouselArrowButtonElement,
	CarouselArrowButtonGroupProps,
	CarouselArrowButtonGroupRef,
	CarouselArrowButtonMouseEvent,
	CarouselArrowButtonProps,
	CarouselArrowButtonRef,
	CarouselArrowIconButtonDefaultElement,
	CarouselArrowIconButtonElement,
	CarouselArrowIconButtonGroupProps,
	CarouselArrowIconButtonGroupRef,
	CarouselArrowIconButtonMouseEvent,
	CarouselArrowIconButtonProps,
	CarouselArrowIconButtonRef,
	CarouselDotProps,
	CarouselDotRef,
	CarouselDotsProps,
	CarouselDotsRef,
	CarouselDotsType,
	CarouselDotType,
	CarouselLeftArrowButtonDefaultElement,
	CarouselLeftArrowButtonElement,
	CarouselLeftArrowButtonProps,
	CarouselLeftArrowButtonRef,
	CarouselLeftArrowIconButtonDefaultElement,
	CarouselLeftArrowIconButtonElement,
	CarouselLeftArrowIconButtonProps,
	CarouselLeftArrowIconButtonRef,
	CarouselLeftLinearGradientProps,
	CarouselLeftLinearGradientRef,
	CarouselLinearGradientProps,
	CarouselLinearGradientRef,
	CarouselOverlayArrowButtonDefaultElement,
	CarouselOverlayArrowButtonElement,
	CarouselOverlayArrowButtonProps,
	CarouselOverlayArrowButtonRef,
	CarouselOverlayArrowIconButtonDefaultElement,
	CarouselOverlayArrowIconButtonElement,
	CarouselOverlayArrowIconButtonProps,
	CarouselOverlayArrowIconButtonRef,
	CarouselOverlayLeftArrowButtonDefaultElement,
	CarouselOverlayLeftArrowButtonElement,
	CarouselOverlayLeftArrowButtonProps,
	CarouselOverlayLeftArrowButtonRef,
	CarouselOverlayLeftArrowIconButtonDefaultElement,
	CarouselOverlayLeftArrowIconButtonElement,
	CarouselOverlayLeftArrowIconButtonProps,
	CarouselOverlayLeftArrowIconButtonRef,
	CarouselOverlayRightArrowButtonDefaultElement,
	CarouselOverlayRightArrowButtonElement,
	CarouselOverlayRightArrowButtonProps,
	CarouselOverlayRightArrowButtonRef,
	CarouselOverlayRightArrowIconButtonDefaultElement,
	CarouselOverlayRightArrowIconButtonElement,
	CarouselOverlayRightArrowIconButtonProps,
	CarouselOverlayRightArrowIconButtonRef,
	CarouselRightArrowButtonDefaultElement,
	CarouselRightArrowButtonElement,
	CarouselRightArrowButtonProps,
	CarouselRightArrowButtonRef,
	CarouselRightArrowIconButtonDefaultElement,
	CarouselRightArrowIconButtonElement,
	CarouselRightArrowIconButtonProps,
	CarouselRightArrowIconButtonRef,
	CarouselRightLinearGradientProps,
	CarouselRightLinearGradientRef
} from './components';
import {
	CarouselArrowButton,
	CarouselArrowButtonGroup,
	CarouselArrowIconButton,
	CarouselArrowIconButtonGroup,
	CarouselDots,
	CarouselLeftArrowButton,
	CarouselLeftArrowIconButton,
	CarouselLeftLinearGradient,
	CarouselLinearGradient,
	CarouselOverlayArrowButton,
	CarouselOverlayArrowIconButton,
	CarouselOverlayLeftArrowButton,
	CarouselOverlayLeftArrowIconButton,
	CarouselOverlayRightArrowButton,
	CarouselOverlayRightArrowIconButton,
	CarouselRightArrowButton,
	CarouselRightArrowIconButton,
	CarouselRightLinearGradient,
	constants as componentsConstants,
	keys as componentsKeys,
	useCarouselDotClasses
} from './components';

// Constants
export const constants = { ...commonConstants, ...componentsConstants };

// Keys
export const keys = { ...commonKeys, ...componentsKeys };

// Utils
export const utils = { ...commonUtils };

// Hooks
export { useCarouselArrowState, useCarouselClasses, useCarouselContext, useCarouselDotClasses, useCarouselManager };

// Components
export {
	Carousel,
	CarouselArrowButton,
	CarouselArrowButtonGroup,
	CarouselArrowIconButton,
	CarouselArrowIconButtonGroup,
	CarouselDots,
	CarouselLeftArrowButton,
	CarouselLeftArrowIconButton,
	CarouselLeftLinearGradient,
	CarouselLinearGradient,
	CarouselOverlayArrowButton,
	CarouselOverlayArrowIconButton,
	CarouselOverlayLeftArrowButton,
	CarouselOverlayLeftArrowIconButton,
	CarouselOverlayRightArrowButton,
	CarouselOverlayRightArrowIconButton,
	CarouselRightArrowButton,
	CarouselRightArrowIconButton,
	CarouselRightLinearGradient
};

// Component Types
export type {
	CarouselArrowButtonDefaultElement,
	CarouselArrowButtonElement,
	CarouselArrowButtonGroupProps,
	CarouselArrowButtonGroupRef,
	CarouselArrowButtonMouseEvent,
	CarouselArrowButtonProps,
	CarouselArrowButtonRef,
	CarouselArrowDirection,
	CarouselArrowIconButtonDefaultElement,
	CarouselArrowIconButtonElement,
	CarouselArrowIconButtonGroupProps,
	CarouselArrowIconButtonGroupRef,
	CarouselArrowIconButtonMouseEvent,
	CarouselArrowIconButtonProps,
	CarouselArrowIconButtonRef,
	CarouselContext,
	CarouselDotProps,
	CarouselDotRef,
	CarouselDotsProps,
	CarouselDotsRef,
	CarouselDotsType,
	CarouselDotType,
	CarouselItem,
	CarouselItems,
	CarouselLeftArrowButtonDefaultElement,
	CarouselLeftArrowButtonElement,
	CarouselLeftArrowButtonProps,
	CarouselLeftArrowButtonRef,
	CarouselLeftArrowIconButtonDefaultElement,
	CarouselLeftArrowIconButtonElement,
	CarouselLeftArrowIconButtonProps,
	CarouselLeftArrowIconButtonRef,
	CarouselLeftLinearGradientProps,
	CarouselLeftLinearGradientRef,
	CarouselLinearGradientProps,
	CarouselLinearGradientRef,
	CarouselOrientation,
	CarouselOverlayArrowButtonDefaultElement,
	CarouselOverlayArrowButtonElement,
	CarouselOverlayArrowButtonProps,
	CarouselOverlayArrowButtonRef,
	CarouselOverlayArrowIconButtonDefaultElement,
	CarouselOverlayArrowIconButtonElement,
	CarouselOverlayArrowIconButtonProps,
	CarouselOverlayArrowIconButtonRef,
	CarouselOverlayLeftArrowButtonDefaultElement,
	CarouselOverlayLeftArrowButtonElement,
	CarouselOverlayLeftArrowButtonProps,
	CarouselOverlayLeftArrowButtonRef,
	CarouselOverlayLeftArrowIconButtonDefaultElement,
	CarouselOverlayLeftArrowIconButtonElement,
	CarouselOverlayLeftArrowIconButtonProps,
	CarouselOverlayLeftArrowIconButtonRef,
	CarouselOverlayRightArrowButtonDefaultElement,
	CarouselOverlayRightArrowButtonElement,
	CarouselOverlayRightArrowButtonProps,
	CarouselOverlayRightArrowButtonRef,
	CarouselOverlayRightArrowIconButtonDefaultElement,
	CarouselOverlayRightArrowIconButtonElement,
	CarouselOverlayRightArrowIconButtonProps,
	CarouselOverlayRightArrowIconButtonRef,
	CarouselProps,
	CarouselRef,
	CarouselRenderIconButtonProps,
	CarouselRightArrowButtonDefaultElement,
	CarouselRightArrowButtonElement,
	CarouselRightArrowButtonProps,
	CarouselRightArrowButtonRef,
	CarouselRightArrowIconButtonDefaultElement,
	CarouselRightArrowIconButtonElement,
	CarouselRightArrowIconButtonProps,
	CarouselRightArrowIconButtonRef,
	CarouselRightLinearGradientProps,
	CarouselRightLinearGradientRef,
	CarouselScrollAmount,
	CarouselVariant
};
