import {
	__DEFAULT_CLEAR_ICON_BUTTON_AS__,
	__DEFAULT_CLEAR_ICON_BUTTON_HAS_TOOLTIP__,
	__DEFAULT_CLEAR_ICON_BUTTON_LABEL__,
	__DEFAULT_CLEAR_ICON_BUTTON_PLACEMENT__
} from './props';

export {
	__DEFAULT_CLEAR_ICON_BUTTON_AS__,
	__DEFAULT_CLEAR_ICON_BUTTON_HAS_TOOLTIP__,
	__DEFAULT_CLEAR_ICON_BUTTON_LABEL__,
	__DEFAULT_CLEAR_ICON_BUTTON_PLACEMENT__
};
